### ISSUE TITLE
Fail to start, (unable to parse Basic Auth credentials)

### ISSUE THREAD

**Issue by thomsh** [zensqlmonitor/influxdb-sqlserver#8]
Hello,
first Influxdb-sqlserver tool looks great and enough for investigate performance issues in sqlserver.

I get some errors after the start but the build was successful. I got :
`"error":"unable to parse Basic Auth credentials"`
details:

```
zensqlmonitor@influx-test-rd:~/influxdb-sqlserver$ ./influxdb-sqlserver -config influxdb-sqlserver.conf 
2016/09/07 15:08:10 [I] Starting influxdb-sqlserver
2016/09/07 15:08:10 [T] <-- Extract | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getmemory.sql | took 49.740763ms
2016/09/07 15:08:10 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse Basic Auth credentials"})
2016/09/07 15:08:10 [T] --> Load    | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getmemory.sql | took 1.412708ms
2016/09/07 15:08:11 [T] <-- Extract | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getmemoryclerksplit.sql | took 91.078659ms
2016/09/07 15:08:11 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse Basic Auth credentials"})
2016/09/07 15:08:11 [T] --> Load    | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getmemoryclerksplit.sql | took 609.055µs
2016/09/07 15:08:11 [T] <-- Extract | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getdatabasesizetrend.sql | took 160.968555ms
2016/09/07 15:08:11 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse Basic Auth credentials"})
2016/09/07 15:08:11 [T] --> Load    | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getdatabasesizetrend.sql | took 734.413µs
2016/09/07 15:08:11 [T] <-- Extract | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getcpu.sql | took 369.066449ms
2016/09/07 15:08:11 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse Basic Auth credentials"})
2016/09/07 15:08:11 [T] --> Load    | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getcpu.sql | took 1.231542ms
2016/09/07 15:08:11 [T] <-- Extract | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getperfmetrics.sql | took 457.508029ms
2016/09/07 15:08:11 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse Basic Auth credentials"})
2016/09/07 15:08:11 [T] --> Load    | 15 sec | Server=192.168.100.111,1433 | sqlscripts/getperfmetrics.sql | took 1.06926ms
^C2016/09/07 15:08:11 [I] Received signal interrupt. shutting down
```

The custom 'influxdb-sqlserver' config file: [https://gist.github.com/theznx/d2e27bed4ef0c9ed7de62bbc916013e0](https://gist.github.com/theznx/d2e27bed4ef0c9ed7de62bbc916013e0)

This credentials are good, i use it with telegraf ([https://github.com/influxdata/telegraf](https://github.com/influxdata/telegraf)), insert & collect works.

There is a type mismatch in the TOML config ? or something wrong? someone got the same issue?

I'm using telegraf too, but the metrics are not identical (even better?), Its not easy to create a good grafana dashbord like yours in 'influxdb-sqlserver'.

**Comment by thomsh** [comment]
Hello, 
For clarification i made the build with `go1.6.3 linux/amd64`  on 2016-09-01

**Comment by zensqlmonitor** [comment]
Hi, maybe some special character in the password ?
Try with another pwd and let me know.
The TOML parser is different than the Telegraf one.

**Comment by zensqlmonitor** [comment]
Hello, any news ?
Can I close this issue ?

**Comment by thomsh** [comment]
Hello,
Sorry, i was a bit offline, 

Today i'm trying to solve the problem, and i found a bypass : disable auth on Influxdb.

First I changed credentials by simple charset [a-z]{8}, on influx + mssql ; and rollback: nothing change
For information, my actual credentials look like [a-Z0-9]{12} on Influxdb  & mssql (On linux: pwgen -1 -A 12)
Username is [a-z]{6} and works with other app.

Finaly I disable auth in influxdb.conf but keep influxdb-sqlserver.conf unchanged
`auth-enabled = false
`
result:
- If I keep auth creds in influxdb-sqlserver.conf and set false for auth-enabled in influxdb.conf and restart both : Everything is working.
- If I re-enable auth (in influxdb.conf) and restart influxdb + influxdb-sqlserver I got similar issue:
  `2016/09/16 13:03:50 [log.go:299 Error()] [E] Error while loading data%!(EXTRA *errors.errorString={"error":"unable to parse authentication credentials"}
  `

So influxdb-sqlserver, is working :)
